---
- name: Make a systemd override directory
  become: true
  file:
    path: /etc/systemd/system/gitlab-runner.service.d
    owner: root
    group: root
    mode: "0755"
    state: directory
- name: Tell systemd to start the runner as the ue5 user
  become: true
  template:
    src: exec_start.j2
    dest: /etc/systemd/system/gitlab-runner.service.d/exec_start.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - daemon reload
    - restart gitlab-runner