---
- name: "#=== 5.1 Check default nameservers"
  shell: grep -c "^nameserver <IP>" /etc/resolvconf/resolv.conf.d/head || true
  register: is_yc_nameserver_correct
  become: true
- name: "#=== 5.2 Check Google nameservers"
  shell: grep -c "^nameserver 8.8.8.8" /etc/resolvconf/resolv.conf.d/head || true
  register: is_google_nameserver_correct
  become: true
- name: "#=== 5.3 Check comment"
  shell: grep -c "^#Managed by Ansible" /etc/resolvconf/resolv.conf.d/head || true
  register: is_comment_exist
  become: true
- name: "#=== 5.4 Add comment"
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/head
    line: "#Managed by Ansible"
  when: is_comment_exist.stdout == "0"
  become: true
- name: "#=== 5.4 Configure default nameservers"
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/head
    line: "nameserver <IP>"
    insertafter: "^#Managed by Ansible"
  when: is_yc_nameserver_correct.stdout == "0"
  become: true
- name: "#=== 5.5 Configure Google nameservers"
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/head
    line: "nameserver 8.8.8.8"
    insertafter: "^#nameserver <IP>"
  when: is_google_nameserver_correct.stdout == "0"
  become: true
- name: "#=== 5.6 Apply resolv.conf"
  shell: resolvconf -u
  become: true
- name: "#=== 5.7 Read resolv.conf"
  command: cat resolv.conf chdir=/etc
  register: cat_resolv_conf
- name: "#=== 5.8 Stdout resolv.conf"
  debug:
    msg: "{{cat_resolv_conf.stdout}}"